// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://evynyovnjoauudinlmid.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV2eW55b3Zuam9hdXVkaW5sbWlkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTExOTE0ODIsImV4cCI6MjA2Njc2NzQ4Mn0.61sV7-oOqD60lOy_fwoH7uhKlF3QMll_y_vVKAPcIt8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);